### ISSUE TITLE
vscode extension

### ISSUE THREAD

**Issue by ghost** [Alhadis/language-sed#1]
Please consider vscode extension ([examples](https://github.com/Microsoft/vscode/tree/master/extensions)).
It boils down to these steps ([source](https://www.reddit.com/r/vscode/comments/7qins6/porting_atom_packages_to_vscode/)):

* Install CSON package in Atom
* Convert CSON grammar file to JSON
* Create a new empty Language extension using [`yo code`](https://code.visualstudio.com/docs/extensions/yocode)
* Copied the contents of the converted JSON into the tmLanguage.json that was generated by yo code
* Install the extension in VSCode

Upon [publishing](https://code.visualstudio.com/docs/extensions/publish-extension), it will appear https://marketplace.visualstudio.com/VSCode (and inside vscode UI).

**Comment by Alhadis** [comment]
What for? Feel free to do it yourself. :grinning: 

Just give credit where it's due (a link to this repository would be fine, I'm not fussed), but other than that, go nuts. Fork. Share. Hack it to shreds. Stick it in a package manager. Go nuts and enjoy.

All my work is released under the [ISC license](https://choosealicense.com/licenses/isc/), so feel free to publish ports for every other [language grammar](https://atom.io/users/Alhadis/packages) I've ever worked on to make them available to VSCode users.

More to the point, I'd rather a VSCode user maintain a port for my work than be obliged to maintain packages for an editor I never use. :wink:

**Comment by dufferzafar** [comment]
I'll try to do the port sometime this week. Will let you know how it goes.
